### ISSUE TITLE
[WIP] Notable bugs on frontend

### ISSUE THREAD

**Issue by Eniamza** [Hound-fm/web#7]
This issue will be updated as I notice new bugs/glitches

- [x] [Glitch] Selected themes radio button gets unselected after changing to another tab and coming back `example - Settings>Podcast>Setting and the radio button will be unchecked` 
- [x] [Glitch] An extra square box is appearing on selecting / clicking Loop and Volume button. This looks shady.
![image](https://user-images.githubusercontent.com/65225917/105675226-fcc8cc00-5f12-11eb-89fc-2bf824c25a2a.png)

- [x] It may not be a glitch but play , pause , next , previous is not clickable  .

**Comment by btzr-io** [comment]
> It may not be a glitch but play , pause , next , previous is not clickable .

Not a bug is the expected behavior since there is no audio to play / navigate. 
Improvement idea:  Use different style so the user is aware that can't interact with it.

**Comment by btzr-io** [comment]
> [Glitch] An extra square box is appearing on selecting / clicking Loop and Volume button. This looks shady.
I think that is a default style from the browser. Since is already using a custom focus style we can ignore / hide the deafult style ( square box )

**Comment by btzr-io** [comment]
> [Enhancement] Volume Button doesn't have a slider which will make it more customizable

I'm trying to add the minimal amount of features first. Feel free to open a different issue for this as a "feature request"

**Comment by Eniamza** [comment]
> I'm trying to add the minimal amount of features first. Feel free to open a different issue for this as a "feature request"

Edited. Will add it to a different issue later

**Comment by Eniamza** [comment]
- [ ] [Bug] hound.fm currently doesn't set any cookie for individual users , as a result If you select a theme and refresh the browser it reverts back to Light theme 
![image](https://user-images.githubusercontent.com/65225917/105679630-ee7dae80-5f18-11eb-9b63-8a75628b59f4.png)

**Comment by Eniamza** [comment]
> Improvement idea: Use different style so the user is aware that can't interact with it.

I may suggest to use a little JS and change the cursor into no entry sign using `onHover` event

**Comment by btzr-io** [comment]
> I may suggest to use a little JS and change the cursor into no entry sign using `onHover` event

That cursor is not commonly used. I think the css styles should be enough for now.

A `disabled` element won't fire any mouse events so `:hover` doesn't work.

**Comment by Eniamza** [comment]
- [ ] [Glitch] Not a serious glitch but it's worth looking into

If you click any of the navigation button several times [For example :- Queue , Music , Latest , Popular] , It redirects to same page each time. To be more clear

Lets say I clicked the queue button 5 times. Without keeping me on the current page it redirects me to the current page and history looks like this : Queue > Queue > Queue> Queue > Queue

So if I click back button to return on the previous page I was before Queue , I would have to click on back button for five times.

**Possible Solution:**

with an `onClick` event , validate if I am currently on the page or not. If on the page do nothing. If not redirect.

**Comment by Eniamza** [comment]
- [ ] [Bug] The Heading containing "Hound.fm" should be clickable and redirecting to homepage. 
![image](https://user-images.githubusercontent.com/65225917/105949331-b56b4880-6096-11eb-895b-f128804e30a8.png)

**Comment by Eniamza** [comment]
- [ ] [UI Glitch] This border shouldn't appear while hovering
![image](https://user-images.githubusercontent.com/65225917/107111607-ab59fe80-687b-11eb-9a21-dec883c23d40.png)

**Comment by Eniamza** [comment]
@btzr-io Hound.Fm still needs a favicon on the browser tab, currently it's showing react logo
